[package]
name = "deployment-app"
version = "0.1.0"
authors = ["dbyr <david.michael.byrne17@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
kubos-app = { path = "../kubos-src/apis/app-api/rust" }
serde_json = "1.0"
